apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-application
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: https://github.com/abhishekghoshh/todo-app-cicd
    targetRevision: feature
    path: argocd
    directory:
      recurse: true
      jsonnet: {}
      exclude: '{**/apps/**,**/argo-apps/**}'
  sources: []
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
