apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:abhishekghoshh/todo-app-cicd.git
    targetRevision: feature
    path: argocd
    directory:
      recurse: true
      jsonnet: {}
      exclude: '{**/apps/**,**/argo-apps/**}'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true