# Use the official Python Alpine image as the base
FROM python:3-alpine

# Install required packages
RUN apk add --no-cache \
    python3-dev py3-virtualenv \
    cairo-dev gcc musl-dev pkgconfig

# Set environment variables
ENV MKDOCS_VERSION=1.6.1 \
    PYTHONUNBUFFERED=1


# Set the working directory
WORKDIR /workspace/docs

# Create a virtual environment
RUN python3 -m venv venv

# Copy requirements.txt
COPY requirements.txt requirements.txt

# Install Python packages in the virtual environment
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

# Copy mkdocs configuration files
COPY mkdocs.yml ./

# Copy the docs directory
COPY docs ./docs

# Expose the port that MkDocs will run on
EXPOSE 8000

# Command to run when starting the container
CMD ["mkdocs", "serve", "-a", "0.0.0.0:8000"]