apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/abhishekghoshh/todo-app-cicd
    targetRevision: dev
    path: argocd/apps/todo-app/overlays/dev
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: todo-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
