apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: todo-app-dev

resources:
- ../../base


transformers: []

# Helm chart definition with values overlay
helmCharts:
  - name: todo-app-chart
    repo: https://registry-1.docker.io/abhishek1009
    version:  1.0.0
    namespace: todo-app-dev
    # base values file
    valuesFile: ../../base/values.yaml
    # overlay values file that will override the base
    additionalValuesFiles:
      - values.yaml
    valuesInline:
      nameOverride: todo-app-dev