apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: todo-app-feature

resources:
- ../../base


transformers: []

# Helm chart definition with values overlay
helmCharts:
  - name: todo-app-chart
    repo: https://registry-1.docker.io/abhishek1009
    version:  1.0.0
    namespace: todo-app-feature
    # base values file
    valuesFiles:
      - ../../base/values.yaml  # (Step 1) Load the common values
      - values.yaml             # (Step 2) Load 'values.yaml' from *this* directory

      # 4. Your inline values (this part was correct)
    valuesInline:
      nameOverride: todo-app-feature