apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "todo-app-chart.fullname" . }}-uploads-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.deployment.app.pvc.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.deployment.app.pvc.size }}