apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "todo-app-chart.mongodb.fullname" . }}-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.deployment.db.pvc.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.deployment.db.pvc.size }}