apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app-chart.mongodb.fullname" . }}-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP # Only reachable inside the cluster
  ports:
    - port: {{ .Values.deployment.db.port }}
      targetPort: mongo
      protocol: TCP
  selector:
    app: {{ include "todo-app-chart.mongodb.fullname" . }}