apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-app-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/abhishekghoshh/todo-app-cicd
    targetRevision: prod
    ref: argorepo
    path: argocd/apps/todo-app/overlays/prod
    kustomize:
      enableHelm: true
  destination:
    server: https://kubernetes.default.svc
    namespace: todo-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
