## See this video for refference : https://www.youtube.com/watch?v=x7f9x30W_dI


# This workflow builds and pushes a Docker image to Docker Hub
name: Build and Push Todo App Docker Image

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on: 
  # workflow_dispatch: {}
  push:
    branches: ["feature"]
    paths:
      - '.github/workflows/docker.yaml'
      - 'src/**'
      - 'Dockerfile'
      - 'go.mod'
      - 'go.sum'
      - 'version'
      - README.md
      - application.yaml



jobs:
  publish_images:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      IMAGE_NAME: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.APP_IMAGE_NAME }}
      # IMAGE_TAG: ${{ github.sha }}
      HEAD_BRANCH: "feature"
      BASE_BRANCH: "dev"
      COMMIT_MSG: ${{ github.event.head_commit.message }}
      REPO_OWNER: ${{ github.repository_owner }}
      GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }} 
      GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup manual ENV
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

          # take the version from version file
          VERSION=$(cat version)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image for todo-app
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ env.VERSION }}
            ${{ env.IMAGE_NAME }}:${{ env.VERSION }}-${{ env.IMAGE_TAG }}
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:cache
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:cache,mode=max
      - name: Update, Commit and push tags to argoCD overlays
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }} 
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          VERSION=$(cat version)
          IMAGE_TAG=${GITHUB_SHA::7}

          git pull --rebase origin $HEAD_BRANCH

          # Update dev values.yaml
          sed -i "s|tag: \".*\"|tag: \"$VERSION-$IMAGE_TAG\"|" argocd/apps/todo-app/overlays/dev/values.yaml
          
          # Update UAT values.yaml
          sed -i "s|tag: \".*\"|tag: \"$VERSION\"|" argocd/apps/todo-app/overlays/uat/values.yaml
          
          # Update prod values.yaml
          sed -i "s|tag: \".*\"|tag: \"$VERSION\"|" argocd/apps/todo-app/overlays/prod/values.yaml

          git add argocd/apps/todo-app/overlays/dev/values.yaml
          git add argocd/apps/todo-app/overlays/uat/values.yaml
          git add argocd/apps/todo-app/overlays/prod/values.yaml

          git commit -m "Update image tags in Helm values.yaml files [skip ci]" || echo "No changes to commit"
          git push origin HEAD:$HEAD_BRANCH
      - name: Create or Update Pull Request
        env:
          HEAD_BRANCH: ${{ env.HEAD_BRANCH }}
          BASE_BRANCH: ${{ env.BASE_BRANCH }}
          COMMIT_MSG: ${{ env.COMMIT_MSG }}
          REPO_OWNER: ${{ env.REPO_OWNER }} 
          GH_TOKEN: ${{ env.GH_TOKEN }}
        run: |
          VERSION=$(cat version)
          IMAGE_TAG=${GITHUB_SHA::7}

          # 1. Check if a PR already exists
          PR_NUMBER=$(gh pr list \
            --base "$BASE_BRANCH" \
            --head "$HEAD_BRANCH" \
            --state open \
            --json number \
            -q '.[0].number')
          
          DETAILED_COMMIT_MESSAGE="Docker image updated with version $VERSION-$IMAGE_TAG 
          Commit message : $COMMIT_MSG"

          if [ -z "$PR_NUMBER" ]; then
            # --- CASE A: Create new PR and Assign ---
            echo "No existing PR found. Creating a new one."
            
            gh pr create \
              --base "$BASE_BRANCH" \
              --head "$HEAD_BRANCH" \
              --title "Deploy changes from $HEAD_BRANCH to $BASE_BRANCH" \
              --body "$DETAILED_COMMIT_MESSAGE" \
              --assignee "$REPO_OWNER"

          else
            # --- CASE B: Update PR Body and Ensure Assignment ---
            echo "Found existing PR #$PR_NUMBER. Appending commit message."
            
            CURRENT_BODY=$(gh pr view "$PR_NUMBER" --json body -q .body)
            
            NEW_BODY="$DETAILED_COMMIT_MESSAGE

            $CURRENT_BODY"
            
            # Update body AND ensure the owner is assigned
            gh pr edit "$PR_NUMBER" \
              --body "$NEW_BODY" \
              --add-assignee "$REPO_OWNER"
          fi



