## See this video for refference : https://www.youtube.com/watch?v=x7f9x30W_dI


# This workflow builds and pushes a Docker image to Docker Hub
name: Build and Push Todo App helm chart to docker Helm Registry

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on: 
  # workflow_dispatch: {}
  push:
    branches: ["feature"]
    paths:
      - 'helm/**'
      - .github/workflows/helm-chart.yaml
  # pull_request:
  #   branches: ["dev", "uat", "prod"]


jobs:
  publish_helm_chart:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      HELM_REGISTRY: ${{ vars.HELM_REGISTRY }}
      HELM_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push the helm chart with version from chart.yaml
        run: |
          # Find chart name from Chart.yaml and remove quotes from chart name if any
          CHART_NAME=$(grep 'name:' helm/Chart.yaml | awk '{print $2}')
          CHART_NAME=${CHART_NAME//\"/}

          # Find chart version from Chart.yaml and # remove quotes from version if any
          CHART_VERSION=$(grep 'version:' helm/Chart.yaml | awk '{print $2}')
          CHART_VERSION=${CHART_VERSION//\"/}

          helm package helm --destination ./packages
          helm push ./packages/$CHART_NAME-$CHART_VERSION.tgz oci://$HELM_REGISTRY/$HELM_USERNAME

      - name: Build and push the helm chart with commit sha as version
        run: |
          # Find chart name from Chart.yaml and remove quotes from chart name if any
          CHART_NAME=$(grep 'name:' helm/Chart.yaml | awk '{print $2}')
          CHART_NAME=${CHART_NAME//\"/}

          # Find chart version from Chart.yaml and # remove quotes from version if any
          CHART_VERSION=$(grep 'version:' helm/Chart.yaml | awk '{print $2}')
          CHART_VERSION=${CHART_VERSION//\"/}

          # strip the github sha to first 7 characters and append to chart version
          CHART_VERSION_FROM_COMMIT=${GITHUB_SHA::7}
          CHART_VERSION_FROM_COMMIT="$CHART_VERSION-$CHART_VERSION_FROM_COMMIT"

          helm package helm --version $CHART_VERSION_FROM_COMMIT --destination ./packages
          helm push ./packages/$CHART_NAME-$CHART_VERSION_FROM_COMMIT.tgz oci://$HELM_REGISTRY/$HELM_USERNAME




