name: Create a Pull Request to Dev Branch
on:
  push:
    branches:
      - feature
    paths:
      - 'argocd/**'

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    env:
      HEAD_BRANCH: "feature"
      BASE_BRANCH: "dev"
      COMMIT_MSG: ${{ github.event.head_commit.message }}
      REPO_OWNER: ${{ github.repository_owner }}
      GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create or Update Pull Request
        env:
          HEAD_BRANCH: ${{ env.HEAD_BRANCH }}
          BASE_BRANCH: ${{ env.BASE_BRANCH }}
          COMMIT_MSG: ${{ env.COMMIT_MSG }}
          REPO_OWNER: ${{ env.REPO_OWNER }} 
          GH_TOKEN: ${{ env.GH_TOKEN }}
        run: |
          # 1. Check if a PR already exists
          PR_NUMBER=$(gh pr list \
            --base "$BASE_BRANCH" \
            --head "$HEAD_BRANCH" \
            --state open \
            --json number \
            -q '.[0].number')
          
          DETAILED_COMMIT_MESSAGE="Commit message : $COMMIT_MSG"

          if [ -z "$PR_NUMBER" ]; then
            # --- CASE A: Create new PR and Assign ---
            echo "No existing PR found. Creating a new one."
            
            gh pr create \
              --base "$BASE_BRANCH" \
              --head "$HEAD_BRANCH" \
              --title "Deploy changes from $HEAD_BRANCH to $BASE_BRANCH" \
              --body "$DETAILED_COMMIT_MESSAGE" \
              --assignee "$REPO_OWNER"

          else
            # --- CASE B: Update PR Body and Ensure Assignment ---
            echo "Found existing PR #$PR_NUMBER. Appending commit message."
            
            CURRENT_BODY=$(gh pr view "$PR_NUMBER" --json body -q .body)
            
            NEW_BODY="$DETAILED_COMMIT_MESSAGE

            $CURRENT_BODY"
            
            # Update body AND ensure the owner is assigned
            gh pr edit "$PR_NUMBER" \
              --body "$NEW_BODY" \
              --add-assignee "$REPO_OWNER"
          fi


